authentication/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
]

login/urls.py
from django.urls import path,include
from login import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

app_name='login'
urlpatterns = [
  
    path('', views.index,name='index' ),
    path('register/',views.register,name='register'),
    path('login/',views.login_page,name='login'),
    path('user_login/',views.user_login,name='user_login'),
    path('user_logout/',views.user_logout,name='user_logout')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserInfo(models.Model):
    
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    facebook_id= models.URLField(blank=True)
    profile_picture= models.ImageField(upload_to='profile_pics',blank=True)
    
    
    def __str__(self):
        
        return self.user.username

login/forms.py
from django import forms
from django.contrib.auth.models import User
from login.models import UserInfo


class UserForm(forms.ModelForm):
    password= forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model= User
        fields=('username','email','password')
    
    

class UserInfoForm(forms.ModelForm):
    class Meta():
        model=UserInfo
        fields=('facebook_id','profile_picture')   

login/views.py
from django.shortcuts import render
from login.forms import UserForm,UserInfoForm
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth.models import User
from login.models import UserInfo
# Create your views here.

def index(request):
    dict={}
    if request.user.is_authenticated:
        current_user=request.user
        user_id= current_user.id
        user_basic_info= User.objects.get(pk=user_id)
        user_more_info= UserInfo.objects.get(user__pk=user_id)
        
        
        dict={'user_basic_info':user_basic_info,'user_more_info':user_more_info}
    
    return render(request,'login_app/index.html',context=dict)


def register(request):
    registered=False
    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        user_info_form= UserInfoForm(data=request.POST)
        
        if user_form.is_valid() and user_info_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            
            user_info= user_info_form.save(commit=False)
            user_info.user= user
            
            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']
            
            user_info.save()    
            registered=True
    else:
        user_form=UserForm()
        user_info_form= UserInfoForm()
        
        
        
    dict={'user_form':user_form,'user_info_form':user_info_form, 'registered':registered}
    
    return render(request,'login_app/register.html',context=dict)
    

def login_page(request):
    return render(request,'login_app/login.html',context={}) 

def user_login(request):
    if request.method=="POST":
        username= request.POST.get('username')
        password= request.POST.get('password')
        
        user=authenticate(username=username,password=password)
        
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('login:index'))
            
            else:
                return HttpResponse("account is not active")
        
        else:
            return HttpResponse("login informations are false")
    
    else:
        return render(request,'login_app/login.html',context={})    
    

@login_required
def user_logout(request):
    logout(request)
    
    return HttpResponseRedirect(reverse('login:index'))    

templates/login_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary  ">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">


              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'login:index' %}">Home</a>
              </li>

              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login:user_logout' %}">Logout</a>
              </li>
               {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login:login' %}">Login</a>
              </li>
              {% endif %}
              
            </form>
          </div>
        </div>
      </nav>

      <div class="container">
         
        {% block body_block %}
        
        
        {% endblock  %}

      </div>
    
</body>
</html>

templates/login_app/index.html
 {% extends "login_app/base.html" %}

 {% block body_block %}
 
{% if user.is_authenticated %}
<p class='mt-4'> hi ,{{ user_basic_info.username }}</p>
<p class='mb-4'>your mail:- {{ user_basic_info.email }}</p>

<p><a href="{{ user_more_info.facebook_id }}"></a></p>

<img src="/media/{{ user_more_info.profile_picture}}" alt="">

{%else%}
<div class='alert alert-danger'> please login first </div>
 {% endif %}
 {% endblock  %}

templates/login_app/login.html
{% extends "login_app/base.html" %}

{% block body_block %}

<h2 class="mt-4">please Login here:- </h2>

<form action="{% url 'login:user_login' %}" method="POST">
<label for="username">Username</label>
<input class="form-control" type="text" name="username" placeholder="enter your name" required >

<label for="password">password</label>
<input class="form-control" type="password" name="password" placeholder="enter password" required>
{% csrf_token %}
<br>
<input type="submit" name="submit" value="login">


</form>


{% endblock  %}

templates/login_app/register.html
{% extends "login_app/base.html" %}
{% load static %}
{% block body_block %}
{% if registered %}

<div class='alert alert-success mt-4'>Congratulation your registration is successfull</div>
{% else %}
<div class="d-flex justify-content-center align-items-center min-vh-100">
    <form class='border border-2 p-3 container' method='POST' enctype='multipart/form-data'>

        {% csrf_token %}
        {{user_form.as_p}}
        {{user_info_form.as_p}}
        
        <input type="submit" value='submit' name='submit'>
        </form>
</div>
{% endif %}

{% endblock  %}